services:
  mysql:
    image: mysql:latest
    container_name: lesson_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: user_lbd
      MYSQL_PASSWORD: pass_lbd
      MYSQL_DATABASE: default_schema
    ports:
      - 3310:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lesson_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    restart: always
    ports:
      - 8183:80
  adminer:
    container_name: lesson_adminer
    image: adminer
    restart: always
    
    ports:
      - 8182:8080